### ISSUE TITLE
RGBM or RGBE?

### ISSUE THREAD

**Issue by polarathene** [oframe/ibl-converter#1]
Looking at the code, RGBM is mentioned as the encoding, but `loadHDR` seems to just be returning the HDR data as RGBE still(there's a mention of RGBA, but my understanding is that the alpha channel 8-bits covers the E exponent values, so no difference other than purpose of channel data).

RGBM is meant to be use the alpha channel as a multiplier instead of an exponent. This afaik requires a constant for the range of 0-M that is mapped to the alpha channels 0-255 values. Such as RGBM16 would support an EV range up to 16 for HDR inputs/exports(still learning about RGBM, I may be incorrect about that constant mapping to EV range). Unity Engine uses RGBM5 iirc, wheras I've also seen 6,7,9 in use, which requires the shader to match that value for reconstruction.

This constant doesn't appear to be used here, so is it really RGBM? Or is the alpha channel encoding the exponent still?

**EDIT:** According to a comment on [this article](http://graphicrants.blogspot.com/2009/04/rgbm-color-encoding.html), the supported EV range is `gamma^M`, although their input doesn't seem to produce the claimed value, `M^gamma` does(`gamma^(M-1)` is close but not quite correct). This gives Unity's M5 a range up to 34.5 from what I understand which should be sufficient for most needs.

**EDIT2:** Further confirmed with the official [Unity docs](https://docs.unity3d.com/Manual/Lightmaps-TechnicalInformation.html), they clear up that the range of 34.5 is for linear space, and 0-5 in gamma space.

**Comment by gordonnl** [comment]
Hey mate,
So sorry for the delay, it turns out that I wasn't watching my own repository...

So, HDR files are in RGBE format, the `HDRLoader` class doesn't actually do any converting, it just reads the binary and changes the format into a usable typed array, so they remain in RGBE format when returned. The conversion to RGBM happens in the [shaders](https://github.com/oframe/ibl-converter/blob/master/src/shaders/SpecularShader.js) on the GPU.

I use a [max value of 6](https://github.com/oframe/ibl-converter/blob/master/src/shaders/SpecularShader.js#L79) for the RGBM conversion - I can't for the life of me remember why 6, but I think there was a reason... Perhaps if it was higher you'd lose precision while not seeing much of a difference.

I hope that answers your questions!
